# Generated by Django 4.0.4 on 2022-07-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ManyToManyField(to='auctions.listings'),
        ),
    ]
