# Generated by Django 4.0.4 on 2022-07-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='listing',
        ),
        migrations.AddField(
            model_name='listings',
            name='comments',
            field=models.ManyToManyField(to='auctions.comments'),
        ),
    ]
