# Generated by Django 4.0.4 on 2022-07-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listings_bid_remove_listings_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bid_id',
        ),
    ]
