# Generated by Django 4.0.4 on 2022-07-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listings_bid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='comments_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
            preserve_default=False,
        ),
    ]
