# Generated by Django 4.0.4 on 2022-07-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listings_comments_id_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
