# Generated by Django 4.0.4 on 2022-07-18 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bids_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing',
        ),
        migrations.AddField(
            model_name='listings',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
            preserve_default=False,
        ),
    ]
