# Generated by Django 4.0.4 on 2022-07-19 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_bids_listing_listings_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='listing',
        ),
        migrations.AddField(
            model_name='listings',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.comments'),
            preserve_default=False,
        ),
    ]
