# Generated by Django 4.0.4 on 2022-07-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_comments_listing_listings_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='comment',
        ),
    ]
