# Generated by Django 4.0.4 on 2022-07-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_listings_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
