# Generated by Django 4.0.4 on 2022-07-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listings_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
    ]
