# Generated by Django 4.0.4 on 2022-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_listings_watchlist_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.listings'),
        ),
    ]
