# Generated by Django 4.0.4 on 2022-07-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_user_watchlist_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(to='auctions.bids'),
        ),
    ]
