# Generated by Django 4.0.4 on 2022-07-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_user_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(blank=True, to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.listings'),
        ),
    ]
