# Generated by Django 4.0.4 on 2022-07-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_user_bids_alter_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_listing',
            field=models.ManyToManyField(blank=True, related_name='created_listings', to='auctions.listings'),
        ),
    ]
