# Generated by Django 4.0.4 on 2022-07-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_user_created_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='comments',
            field=models.ManyToManyField(blank=True, to='auctions.comments'),
        ),
    ]
